export const GET_FISH_REQUEST = "GET_FISH_REQUEST";
export const GET_FISH_SUCCESS = "GET_FISH_SUCCESS";
export const GET_FISH_FAILURE = "GET_FISH_FAILURE";

export const ADD_FISH_REQUEST = "ADD_FISH_REQUEST";
export const ADD_FISH_SUCCESS = "ADD_FISH_SUCCESS";
export const ADD_FISH_FAILURE = "ADD_FISH_FAILURE";

export const EDIT_PRODUCT_REQUEST = "EDIT_PRODUCT_REQUEST";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_FAILURE = "EDIT_PRODUCT_FAILURE";

export const GET_CURRENT_PRODUCT_REQUEST = "GET_CURRENT_PRODUCT_REQUEST";
export const GET_CURRENT_PRODUCT_SUCCESS = "GET_CURRENT_PRODUCT_SUCCESS";
export const GET_CURRENT_PRODUCT_FAILURE = "GET_CURRENT_PRODUCT_FAILURE";
