export const SET_SIGNUP_DATA_REQUEST = "SET_SIGNUP_DATA_REQUEST";
export const SET_SIGNUP_DATA_SUCCESS = "SET_SIGNUP_DATA_SUCCESS";
export const SET_SIGNUP_DATA_FAILURE = "SET_SIGNUP_DATA_FAILURE";

export const GET_SIGNUP_DATA_REQUEST = "GET_SIGNUP_DATA_REQUEST";
export const GET_SIGNUP_DATA_SUCCESS = "GET_SIGNUP_DATA_SUCCESS";
export const GET_SIGNUP_DATA_FAILURE = "GET_SIGNUP_DATA_FAILURE";
